# Generated by Django 4.0.6 on 2022-07-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('student_class', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI')], default='VI', max_length=5)),
                ('phone_number', models.CharField(max_length=15)),
                ('division', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=128)),
                ('mother_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students_list',
                'ordering': ('name',),
            },
        ),
    ]
