# Generated by Django 4.0.6 on 2022-07-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_students_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='division',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
