# Generated by Django 4.0.3 on 2022-03-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Blog Post', max_length=128)),
            ],
            options={
                'db_table': 'web_ContentType',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='customers/')),
            ],
            options={
                'verbose_name': 'Customer',
                'db_table': 'web_Customers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='features/')),
                ('icon', models.FileField(upload_to='features/icons/')),
                ('icon_background', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('testimonial_des', models.TextField()),
                ('testimonial_author', models.CharField(max_length=255)),
                ('author_designation', models.CharField(max_length=255)),
                ('testimonial_logo', models.FileField(upload_to='features/testimonial_logos/')),
            ],
            options={
                'db_table': 'web_Features',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MarketingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='marketing/')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('logo', models.FileField(upload_to='products/logos')),
                ('button_bg', models.CharField(default='color', max_length=128)),
                ('bg_color', models.CharField(default='color', max_length=128)),
            ],
            options={
                'db_table': 'web_Product',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonial/images/')),
                ('logo', models.FileField(blank=True, null=True, upload_to='testimonial/logos/')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=128)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'web_Testimonial',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VideoBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='videoBlogs/images/')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.FileField(upload_to='videoBlogs/logos/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.contenttype')),
            ],
            options={
                'db_table': 'web_Blogs',
                'ordering': ['id'],
            },
        ),
    ]
