# Generated by Django 4.0.3 on 2022-03-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content_type',
            field=models.CharField(choices=[('blog_post', 'Blog Post'), ('webinar', 'Webinar'), ('report', 'Report')], max_length=128),
        ),
        migrations.DeleteModel(
            name='ContentType',
        ),
    ]
