# Generated by Django 4.0.3 on 2022-03-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_blog_content_type_delete_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoblog',
            name='image',
            field=models.FileField(upload_to='videoBlogs/images/'),
        ),
    ]
