# Generated by Django 4.0.3 on 2022-03-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_videoblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content_type',
            field=models.CharField(choices=[('blog post', 'Blog Post'), ('webinar', 'Webinar'), ('report', 'Report')], max_length=128),
        ),
    ]
