# Generated by Django 4.0.3 on 2022-03-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_product_bg_color_remove_product_button_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('company_size', models.CharField(choices=[('1', '1- 10'), ('2', '11- 50'), ('3', '51- 200'), ('4', '201- 500')], max_length=128)),
                ('industry', models.CharField(choices=[('1', 'Agriculture'), ('2', 'Banking & Finance'), ('3', 'Bussiness Service & Software')], max_length=128)),
                ('job_role', models.CharField(choices=[('1', 'C-Suite'), ('2', 'VP')], max_length=128)),
                ('country', models.CharField(choices=[('us', 'UNITED STATES'), ('albania', 'Albania'), ('afghanistan', 'Afghanistan')], max_length=128)),
                ('user_agreement', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'web_Contact',
                'ordering': ['id'],
            },
        ),
    ]
