# Generated by Django 4.0.3 on 2022-03-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_promoters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('faq_type', models.CharField(choices=[('rent_tracking', 'Rent Tracking'), ('new_deposit', 'New Deposit'), ('existing_deposit', 'Existing Deposit')], max_length=128)),
            ],
        ),
    ]
