# Generated by Django 4.0.3 on 2022-03-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='image', upload_to='testimonials/'),
            preserve_default=False,
        ),
    ]
