# Generated by Django 4.0.3 on 2022-03-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_testimonial_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promoters',
            options={'verbose_name': 'Promoter', 'verbose_name_plural': 'Promoters'},
        ),
    ]
