# Generated by Django 4.0.3 on 2022-03-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_promoters_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promoters',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Promoter', 'verbose_name_plural': 'Promoters'},
        ),
        migrations.AlterModelTable(
            name='promoters',
            table='web_Promoters',
        ),
    ]
